import type { Metadata } from "next";
import { Kumbh_Sans, Geist } from "next/font/google";

import CartContextProvider from '@/store/cart-context';
import Navbar from '@/components/Navbar';
import "./globals.css";
import { cn } from "@/lib/utils";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

const kumbhSans = Kumbh_Sans({
  subsets: ["latin"]
})


export const metadata: Metadata = {
  title: "Product Page",
  description: "Generated by next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", kumbhSans.className)}
    >
      <body>
        <CartContextProvider>
          <div className="flex flex-col min-h-screen md:h-screen">
            <Navbar />
            {children}
          </div>
        </CartContextProvider>
      </body>
    </html>
  );
}
