import type { Metadata } from "next";
import { Kumbh_Sans } from "next/font/google";

import Navbar from '@/components/Navbar';
import "./globals.css";

const kumbhSans = Kumbh_Sans({
  variable: "--font-kumbg-sans",
  subsets: ["latin"]
})


export const metadata: Metadata = {
  title: "Product Page",
  description: "Generated by next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${kumbhSans.variable} h-full antialiased`}
    >
      <body>
        <div className="w-full min-h-screen md:max-w-[1440px] md:mx-auto">
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  );
}
