import type { Metadata } from "next";
import { Kumbh_Sans } from "next/font/google";

import CartContextProvider from '@/store/cart-context';
import Navbar from '@/components/Navbar';
import "./globals.css";

const kumbhSans = Kumbh_Sans({
  variable: "--font-kumbg-sans",
  subsets: ["latin"]
})


export const metadata: Metadata = {
  title: "Product Page",
  description: "Generated by next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${kumbhSans.variable} h-full antialiased`}
    >
      <body>
        <CartContextProvider>
          <div className="relative flex flex-col w-full min-h-screen md:h-screen md:max-w-360 md:mx-auto">
            <Navbar />
            {children}
          </div>
        </CartContextProvider>
      </body>
    </html>
  );
}
